name: Code Quality

on:
  push:
  workflow_dispatch:

jobs:
  isort:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          python -m pip install pre-commit awscli matplotlib scipy ooipy

      - name: Run isort hook
        run: |
          pre-commit install
          pre-commit run isort --all-files

  black:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit

      - name: Run Black hook
        run: |
          pre-commit install
          pre-commit run black --all-files

  pyupgrade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit

      - name: Run pyupgrade hook
        run: |
          pre-commit install
          pre-commit run pyupgrade --all-files

  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit

      - name: Run flake8 hook
        run: |
          pre-commit install
          pre-commit run flake8 --all-files
